kind: pipeline
type: docker
name: build-and-publish-linux

trigger:
  event:
    - tag

steps:
- name: publish
  image: gradle:jdk17

  resources:
    limits:
      memory: 2G
      cpu: 1.5
  
  environment:
    GPR_USER:
      from_secret: GITHUB_USERNAME
    GPR_KEY:
      from_secret: GITHUB_PAT
      
  commands:
    - echo "Enabling 32-bit architecture and updating package lists..."
    - dpkg --add-architecture i386
    - apt-get update -y
    
    - echo "Installing native build dependencies for both 64-bit and 32-bit..."
    - apt-get install -y \
        g++-multilib \
        libx11-dev \
        libxrandr-dev \
        libxcursor-dev \
        libgl-dev \
        libwayland-dev \
        libx11-dev:i386 \
        libxrandr-dev:i386 \
        libxcursor-dev:i386 \
        libgl-dev:i386 \
        libwayland-dev:i386
    
    - chmod +x ./gradlew
    
    - echo "Building and publishing..."
    - ./gradlew publish