kind: pipeline
type: docker
name: build-and-publish-linux

trigger:
  event:
    - tag

steps:
- name: build
  image: gradle:jdk17
  resources:
    limits:
      memory: 2G
      cpu: 1.5
  commands:
    - echo "Enabling 32-bit architecture and updating package lists..."
    - dpkg --add-architecture i386
    - apt-get update -y
    
    - echo "Installing native build dependencies for both 64-bit and 32-bit..."
    - >
      apt-get install -y
      g++-multilib
      libx11-dev
      libxrandr-dev
      libxcursor-dev
      libgl-dev
      libwayland-dev
      libx11-dev:i386
      libxrandr-dev:i386
      libxcursor-dev:i386
      libgl-dev:i386
      libwayland-dev:i386
    
    - chmod +x ./gradlew
    
    - echo "Building and publishing to local repo directory..."
    - ./gradlew publish

- name: create-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_PAT
    files:
      - "**/build/repo/**"
    title: ${DRONE_TAG}
    note: "Automated release for version ${DRONE_TAG}"
  when:
    event:
      - tag